name: "Composite Action Test"
description: "Testing composite action envs"
author: "Mitchell"

inputs:
  commit_message:
    description: If set, this action will invoke stefanzweifel/git-auto-commit-action with the given commit message.
    default: ""
  go_version:
    description: Go version used to install Yampl
    default: "1.19"
  yampl_version:
    description: Yampl version to install
    default: latest

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
    - name: Install YAMPL
      shell: bash
      run: go install github.com/clevyr/yampl@${{ inputs.yampl_version }}
    - name: Insert GH Actions dir into the path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Template Values
      run: main.sh
      shell: bash
    - name: Commit changes
      if: inputs.commit_message
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.commit_message }}