name: "Composite Action Test"
description: "Testing composite action envs"
author: "Mitchell"

inputs:
  commit_message:
    description: If set, this action will invoke stefanzweifel/git-auto-commit-action with the given commit message.
    default: ":arrow_up: Create temp deployment for PR ${{ github.event.pull_request.number }}"
  yampl_values:
    required: true
  dest-path:
    required: true
  template-path:
    required: true
  repository:
    required: true
  branch:
    required: false
  repo-token: 
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.repo-token }}
    - name: Copy template to destination
      run: mkdir -p ${{ inputs.dest-path }}/temp${{ github.event.pull_request.number }} && cp -r ${{ inputs.template-path }}/* ${{ inputs.dest-path }}/temp${{ github.event.pull_request.number }}
      shell: bash
    - name: Template with YAMPL
      uses: clevyr/yampl-action@main
      with:
        file: ${{ inputs.dest-path }}/temp${{ github.event.pull_request.number }}/**/*.yaml
        values: ${{ inputs.yampl_values }}
        commit_message: ${{ inputs.commit_message }}
        commit_branch: ${{ inputs.branch }}