name: "Composite Action Delete"
description: "Testing temp env delete"
author: "Mitchell"

jobs:
  get-pr:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.findPr.outputs.number }}
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
  delete-temp:
    runs-on: ubuntu-latest
    needs: get-pr
    if: needs.get-pr.outputs.pr
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOYMENT_REPO }}
          token: ${{ secrets.PAT }}
      - name: "Check file existence"
        id: filecheck
        uses: andstor/file-existence-action@v2
        with:
          files: "apps/test/temp${{needs.get-pr.outputs.pr}}/app/helmrelease.yaml"
      - name: Delete temp directory
        if: steps.filecheck.outputs.files_exists == 'true'
        run: rm -rf apps/test/temp${{needs.get-pr.outputs.pr}}
        shell: bash
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Delete temp deployment for PR ${{needs.get-pr.outputs.pr}}
          branch: main