name: "Create Temp Environment"

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      dest-path:
        required: true
        type: string
      template-path: 
        required: true
        type: string
      yampl:
        required: true
        type: string
    secrets:
      repo-token:
        required: true
jobs:
  create-temp:
    name: Create Temp 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.repo-token }}
      - name: 
        uses: rmitchellscott/composite-action-test/create@main
        with: 
          commit_message: ":arrow_up: Create temp deployment for PR ${{ env.PR_NUMBER }} from commit ${{ steps.short-sha.outputs.sha }}"